FROM node:20-alpine AS builder

WORKDIR /app

# نصب ابزارهای مورد نیاز
RUN npm install -g pnpm

# کپی پکیج‌ها
COPY package.json pnpm-workspace.yaml ./
COPY server/package.json ./server/

RUN pnpm install --filter daftar-server --frozen-lockfile=false

# کپی سورس کد و پریزما
COPY server ./server

WORKDIR /app/server
RUN npx prisma generate
RUN pnpm build

# مرحله نهایی پروداکشن
FROM node:20-alpine AS runner

WORKDIR /app
RUN npm install -g pnpm

COPY --from=builder /app/package.json /app/pnpm-workspace.yaml ./
COPY --from=builder /app/server/package.json ./server/
COPY --from=builder /app/server/dist ./server/dist
COPY --from=builder /app/server/prisma ./server/prisma
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/server/node_modules ./server/node_modules

WORKDIR /app/server
EXPOSE 3000

CMD ["node", "dist/app.js"]
